title: Grow Kitty
description: Gamified Habit Tracking meets Virtual Pet Growth
baseurl: "/GrowKitty"
url: "https://kimdohun020817.github.io"

theme: null   # Custom theme enabled

plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - name: Home
    link: "/"
  - name: Demo
    link: "/demo.html"
  - name: Features
    link: "/features"
  - name: Documentation
    link: "https://growkitty.readthedocs.io"
  - name: Community
    link: "/community"
  - name: Contact
    link: "/contact"
